---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates Rocky and CentOS
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution in ["Rocky", "CentOS"]

  - name: install updates Ubuntu and Debian
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution in ["Ubuntu", "Debian"]

- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php for Ubuntu and Debian servers
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: install apache and php for Rocky and CentOS servers
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution in ["Rocky", "CentOS"]

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package Rocky and CentOS servers
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution in ["Rocky", "CentOS"]

  - name: install mariadb package Ubuntu and Debian servers
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution in ["Ubuntu", "CentOS"]

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    package:
      name: samba
      state: latest
