---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates Rocky and CentOS
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution in ["Rocky", "CentOS"]

  - name: install updates Ubuntu and Debian
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution in ["Ubuntu", "Debian"]

- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php for Ubuntu and Debian servers
    tags: apache,apache2,ubuntu,debian
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: install apache and php for Rocky and CentOS servers
    tags: apache,centos,rocky,httpd
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution in ["Rocky", "CentOS"]

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package Rocky and CentOS servers
    tags: centos,rocky,db,mariadb
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution in ["Rocky", "CentOS"]

  - name: install mariadb package Ubuntu and Debian servers
    tags: db,ubuntu,debian,mariadb 
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution in ["Ubuntu", "CentOS"]

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest
